version: '3.1'

services:
    datastore:
        image: mongo
        ports:
            - 27017:27017

    database:
        image: postgres
        ports:
            - 5433:5432
        environment:
            POSTGRES_DB: "shippy.users"

    consignment-cli:
        build: ./consignment-cli
        depends_on:
            - consignment-service
            - vessel-service
    
    consignment-service:
        build: ./consignment-service
        depends_on:
            - datastore
            - vessel-service
        ports:
            - 50051:50051
        environment:
            MICRO_ADDRESS: ":50051"
            DB_HOST: "datastore:27017"
            DISABLE_AUTH: "true"

    vessel-service:
        build: ./vessel-service
        depends_on:
            - datastore
        ports:
            - 50052:50051
        environment:
            MICRO_ADDRESS: ":50051"
            DB_HOST: "datastore:27017"

    user-cli:
        build: ./user-cli
        command: "./wait-for-it.sh user-service:50051 -t 5 -- \
                  ./user-cli command --name=\"pm\" --email=\"pm@pm.com\" --password=\"test\" --company=\"BBC\""
        depends_on:
            - user-service

    user-service:
        build: ./user-service
        command: "./wait-for-it.sh database:5432 -t 5 -- ./user-service"
        depends_on:
            - database
        ports:
            - 50053:50051
        environment:
            MICRO_ADDRESS: ":50051"
            DB_HOST: "database"
            DB_PORT: "5432"
